### PR TITLE
Add option to append context menu to a specific element

### PR DESCRIPTION
**Pull request by lukaszkostrzewa**
I would like to add an option to the plugin which will allow appending context menu to a specific element. By default, it will be `body` (just as it is now). 

I'm using the plugin within Angular and I don't want to include cytoscape.js-context-menus CSS in the global stylesheet. Instead, I would like to add it on a component level. Additionally, such an option exists also for instance in bootstrap tooltips.

### CODE REVIEW

**Comment by metincansiper** [comment]
@lukaszkostrzewa I think that these changes may be problematic in some cases. In this (https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus/blob/master/cytoscape-context-menus.js#L207) and the following lines we calculate the ```left``` and ```top``` coordinates relative to body (If I am not wrong). Then we set ```left``` and ```top``` style of the context menu to that calculated values (As far as I know while reseting them we specify the position of context menu relative to the its closest ancestor. With these changes the closest ancestor may not be the body according to the user option). If we apply your changes while we are still calculating that values based on body, then context menu may appear on wrong coordinates? Do you agree?

**Comment by lukaszkostrzewa** [comment]
@metincansiper you are right. In my case, it only worked because my container had 100% width and height of the body. I've pushed the fix – unless we are appending to the body, we don't add container's offset. 

Thanks for noticing this! :)

**Comment by metincansiper** [comment]
@lukaszkostrzewa As far as I understand this container option should point to actual container of cy instance to work properly. Am I right? If so I think that we do not need to have this container option. Instead of having it we can always append ```$cxtMenu``` to ```cy.container()``` and we can use ```renderedPos.x``` and ```renderedPos.y``` for ```left``` and ```right``` respectively (as you do inside ```if(opts.container)```). 

What do you think about doing in that way? Do you think that it will work?

**Comment by lukaszkostrzewa** [comment]
Hi Metin, 

I tried to append context menu to `cy.container()`, but with no luck :) I encountered two problems when a menu was appended to `cy.container()` and when clicking on a menu option: 

1. `tapstart` event was triggered, the menu was hidden (and scratch properties were deleted – [handler function registered in `bindCyEvents`](https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus/blob/master/cytoscape-context-menus.js#L186)) and the event handler was not invoked at all
2. even if it's resolved (* for example in such a way) there was still problem that nodes were deselected before event handler execution (therefore `cy.$(':selected')` in event handler always returned empty list)

*)
```
cy.on('tapstart', eventCyTapStart = function(event) {
  if ($(event.originalEvent.target).hasClass(menuItemCSSClass)) {
     return;
  }
  (...)
}
```

Given these issues, I think that it's too much effort to make it work and it will be better to leave it as it is now (i.e. append menu always to `body`). So I'm closing this PR. Thanks for your assistance and time! :) 

Regards,
Lukasz

**Pull request closed without merging**
