### PR TITLE
fixed #17 context menu repositions if off screen to the right or bottom

### LINKED ISSUE #17: Context-menus out of the screen #1920
Report by @qtttttttttting

**Issue type**

Bug report

**Environment info**

- Cytoscape.js version :  v3.1.2
- Browser/Node.js & version : chrome 59.0.3071.115

**Current (buggy) behaviour**

I use the context-menus of UI extension  , but when the node is on the right or bottom of the screen ,the context-menus will beyond the screen .And I see the source code ,it does not consider this situation.

207          var containerPos = $(cy.container()).offset();
208          var renderedPos = event.renderedPosition || event.cyRenderedPosition;
209
210          var left = containerPos.left + renderedPos.x;
211          var top = containerPos.top + renderedPos.y;
212
213          $cxtMenu.css('left', left);
214          $cxtMenu.css('top', top);

**Desired behaviour**

**Minimum steps to reproduce**

### PR DESCRIPTION
**Pull request by pumpadump**
Encountered the same issue as #17 this change should handle these cases, see demo.html

### CODE REVIEW

**Comment by pumpadump** [comment]
Thanks for merging, when is the next release on npm planned? Just asking to see if i should wait or use my own patch in my project.

**Comment by kinimesi** [comment]
@pumpadump The pull request is reverted due to a bug. This bug occurs when menu sizes are different.
Reproduce: 
1. In demo 1, right click on node `Jerry`, then click on canvas to clear context menu.
2. Go to left-bottom and right click on canvas. The context menu will appear in wrong position. This is specially problematic when one of the context menus is long (have many items) and the other one is short.

**Comment by pumpadump** [comment]
Ah ok it seems that the inital context menu includes 4 additional hidden elements that are taken into consideration when calling $cxtMenu.height() the first time. On the second click the height is returned correctly. Hm so we need a way to calculate the correct height in the adjustCxtMenu function.

**Comment by ugurdogrusoz** [comment]
@pumpadump Please fix this asap since we'd like to get a new release out this week.

**Comment by pumpadump** [comment]
@ugurdogrusoz i wont be able to find time to fix it this week

**Comment by rkaliyug** [comment]
I am facing same issue and does not look like fixed in latest. can you please throw some light on it?

**Pull request merged**
