### PR TITLE
Fix memory leak connected with eventListener

### PR DESCRIPTION
**Pull request by pmierkowski**
In file `cytoscape-context-menus.js` in line 99 there is added listener to **document** element:
`document.addEventListener('mouseup', onClick)`
but in the line 189 listener was removed from **document.body** element 
`document.body.removeEventListener('mouseup', getScratchProp('hideOnNonCyClick'))` 
which cause memory leaks in Angular 10 pomimo despite of use **destroy**.

### CODE REVIEW

**Comment by ugurdogrusoz** [comment]
@pmierkowski Thanks for your PR. This should be done to the "unstable" branch but perhaps the changes are minor enough for @canbax to do them directly in the "unstable" branch after a review.

**Comment by pmierkowski** [comment]
@ugurdogrusoz Thanks for the quick reply. If that's a problem, I can do PR to "unstable".

**Comment by ugurdogrusoz** [comment]
That'd be great, thanks

**Comment by pmierkowski** [comment]
@ugurdogrusoz Done: https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus/pull/58

**Pull request closed without merging**
