### PR TITLE
Append context menu to cytoscape container instead of body

### PR DESCRIPTION
**Pull request by rparent**
This is a backport of #50 on the right branch and without `jQuery`.

I have built and commited the new version, I don't know if you want to build for each PR or only at releases ?

### CODE REVIEW

**Review by msalihaltun — COMMENTED** [review]
Changes seem fine and function correctly in the demo but when merged with Newt causes a side-effect that breaks "remove all anchors" functionality. Not sure why yet. I think we should revisit this after edge-editing release.

**Comment by hasanbalci** [comment]
@rparent @msalihaltun I noticed a side affect of this PR. For example, in the demo, if we choose "select all nodes" from the root menu, all nodes are chosen as normal. Then if we choose "select all edges", all edges are chosen but all nodes are unselected unexpectedly. In the current unstable branch, all nodes stay as selected. I think, since context-menu is now appended to cy container, cy detects a click on itself and unselects the nodes. I played with z-index values of context-menus to prevent this behavior but couldn't manage to fix it.

**Comment by msalihaltun** [comment]
>  I think, since context-menu is now appended to cy container, cy detects a click on itself and unselects the nodes. I played with z-index values of context-menus to prevent this behavior but couldn't manage to fix it.

@hasanbalci @rparent In this case, maybe preventing bubbling on the menu item click events with `preventDefault()` can solve it by stopping the cy container from detecting the click event on itself.

**Comment by rparent** [comment]
@hasanbalci @msalihaltun I just pushed a commit to [prevent mouse/touch events](https://github.com/iVis-at-Bilkent/cytoscape.js-context-menus/pull/51/commits/cb4ed3e4a8ba6ab57de0017088f9b894ed5b1bde#diff-18c4e564b070272689ada90578d3baa1R91) from being propagated when they occur inside the context menu, it seems to fix those unintended click issues. Does it fix your demo ?

**Comment by msalihaltun** [comment]
@rparent @hasanbalci Seems fixed now for me. Will test with Newt soon. 

Also just noticed an error that existed before this PR. Probably unrelated to this as I get the error on [this demo](https://raw.githack.com/iVis-at-Bilkent/cytoscape.js-context-menus/unstable/demo.html), may open a seperate issue for it. In the demos, when select all options are used and elements are manually unselected -via click on anywhere for example-, the option that appears on the context menu is still "unselect", even though elements are unselected already. Seems to be an oversight.

**Comment by hasanbalci** [comment]
@rparent I also tried in the demo and it's working correctly now, thanks!

**Comment by msalihaltun** [comment]
@hasanbalci Works correctly in Newt after the changes as well. I think this can be merged now.

**Comment by rparent** [comment]
@hasanbalci @msalihaltun Thanks for the merge ! 

Just to know, do you have a rough idea of the delay before this gets released ?

**Comment by msalihaltun** [comment]
@rparent Thank you for your contribution. We are planning to have a new release of this extension soon that should include this change.

**Pull request merged**
